services:
  notify:
    build: .
    env_file:
      - .env
    ports:
      - 8090:8090
    restart: always
    depends_on:
      - redis
  runner:
    build: .
    env_file:
      - .env
    entrypoint: "python /src/slack_runner.py"
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: always
